### PR TITLE
tvOS support

### PR DESCRIPTION
**Pull request by RomanPodymov**
Hello.
Thank you for CombineCocoa.
CombineCocoa now supports tvOS.

### CODE REVIEW

**Comment by RomanPodymov** [comment]
Hello @freak4pc 
Any updates?

**Comment by markst** [comment]
+1

**Comment by markst** [comment]
Would be cool to add: https://developer.apple.com/documentation/uikit/uicollectionviewdelegate/1618081-collectionview

**Comment by RomanPodymov** [comment]
> Would be cool to add: https://developer.apple.com/documentation/uikit/uicollectionviewdelegate/1618081-collectionview

Hello @markst 
First of all we need to merge this pull request.

**Comment by batkov** [comment]
FYI, this PR has not been properly tested and is not working on tvOS as expected. 
I found that `UIButton.tapPublisher` is not functioning.

Probably more issues will arise.

**Comment by markst** [comment]
> I found that `UIButton.tapPublisher` is not functioning.

You shouldn't be using "UIControlEvents.TouchUpInside" on tvOS, since that doesn't do what you might expect: you probably want to use "UIControlEvents.PrimaryActionTriggered" instead.

TouchUpInside is triggered by actual touches, which isn't really what you wanted here: if you want the Select button press on the remote to trigger your button, you should use PrimaryActionTriggered.

**Comment by markst** [comment]
@freak4pc - are you happy to add us to as a maintainer to this repo as you don't need to be maintaining this repo? It's last merge was two years ago.

**Comment by markst** [comment]
Why did we close this?

**Pull request closed without merging**
